OPENAI_API_KEY: "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"
PINECONE_API_KEY: "pcsk_3XVhhn_AjEKPSwuujGsrUQpasFcnbfo6Q77XW4Evxev4ZRV1KDCfKcNziHut1YDPwm9Brk"

